>-*-*-*-*-*-*-<
LR: 5e-05, WD: 0.001, Seed: 176060, BS: 4, Max Length: 60, Gradual Unfreeze: False, Discriminative Finetuning: False, Weight: None
>-*-*-*-*-*-*-<
Traceback (most recent call last):
  File "example.py", line 608, in <module>
    results = main(lr=lr, wd=wd, seed=seed, name=args.name, weight=weight, bs=bs, max_length=max_length, gradual_unfreeze=gradual_unfreeze, discriminate=discriminate)
  File "example.py", line 333, in main
    with open(path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/finBERT/gpt_downstream/public_gridsearch/log_name_hf_public_ckpt_lr_5e-05_wd_0.001_seed_176060_bs_4_max_length_60_gradualunfreeze_False_discriminate_False.txt'
Traceback (most recent call last):
  File "example.py", line 608, in <module>
Traceback (most recent call last):
  File "example.py", line 608, in <module>
    results = main(lr=lr, wd=wd, seed=seed, name=args.name, weight=weight, bs=bs, max_length=max_length, gradual_unfreeze=gradual_unfreeze, discriminate=discriminate)
  File "example.py", line 333, in main
    with open(path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/finBERT/gpt_downstream/public_gridsearch/log_name_hf_public_ckpt_lr_5e-05_wd_0.001_seed_176060_bs_4_max_length_60_gradualunfreeze_False_discriminate_False.txt'
    results = main(lr=lr, wd=wd, seed=seed, name=args.name, weight=weight, bs=bs, max_length=max_length, gradual_unfreeze=gradual_unfreeze, discriminate=discriminate)
  File "example.py", line 333, in main
    with open(path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/finBERT/gpt_downstream/public_gridsearch/log_name_hf_public_ckpt_lr_5e-05_wd_0.001_seed_176060_bs_4_max_length_60_gradualunfreeze_False_discriminate_False.txt'
Traceback (most recent call last):
  File "example.py", line 608, in <module>
    results = main(lr=lr, wd=wd, seed=seed, name=args.name, weight=weight, bs=bs, max_length=max_length, gradual_unfreeze=gradual_unfreeze, discriminate=discriminate)
  File "example.py", line 333, in main
    with open(path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/finBERT/gpt_downstream/public_gridsearch/log_name_hf_public_ckpt_lr_5e-05_wd_0.001_seed_176060_bs_4_max_length_60_gradualunfreeze_False_discriminate_False.txt'
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'example.py', '--name', 'hf_public_ckpt', '--weight', 'public_ckpt', '--lr', '5e-5', '--wd', '0.001', '--seed', '176060', '--bs', '4', '--max_length', '60', '--gradual_unfreeze', 'False', '--discriminate', 'False']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Killing subprocess 1858
Killing subprocess 1859
Killing subprocess 1860
Killing subprocess 1861
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/accelerate/commands/accelerate_cli.py", line 41, in main
    args.func(args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/accelerate/commands/launch.py", line 307, in launch_command
    multi_gpu_launcher(args)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/accelerate/commands/launch.py", line 151, in multi_gpu_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'torch.distributed.launch', '--use_env', '--nproc_per_node', '4', 'example.py', '--name', 'hf_public_ckpt', '--weight', 'public_ckpt', '--lr', '5e-5', '--wd', '0.001', '--seed', '176060', '--bs', '4', '--max_length', '60', '--gradual_unfreeze', 'False', '--discriminate', 'False']' returned non-zero exit status 1.
